# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a58c75e8885e3a07aabfb8b8300ca67bec5fb8eaf66a7b725288fd511e85e466b0078566316c04fbc04a27191211af2e413b1e96e66780332b1e312d410920

test:
  secret_key_base: c243524c786bf6921754a041efaf18f6458f62126cabf25b4e225f2774ae9ae63683c30a1baf243110aba4b2e84b7ac96f8673d5423dc47e39b9c377bc7f26a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
